### ISSUE TITLE
Awful output.  Library problem?  Really need help

### ISSUE THREAD

**Issue by djvs** [coolwanglu/pdf2htmlEX#477] opened 2015-02-23 20:16 UTC
Having the following output problems 

![2015-02-17-112011_541x447_scrot](https://cloud.githubusercontent.com/assets/2954343/6231960/fe32a564-b696-11e4-94eb-d362f0e5e612.png)

From this document:

http://djvs.co/Untitleddocument.pdf

HTML output here:

http://djvs.co/Untitleddocument.html

Running only:

    pdf2htmlEX Untitleddocument.pdf

Version info:

    pdf2htmlEX -v    
    pdf2htmlEX version 0.12
    Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
    Libraries: 
      poppler 0.24.5
      libfontforge 20141104
      cairo 1.13.1
    Default data-dir: /usr/share/pdf2htmlEX
    Supported image format: png jpg svg

On Ubuntu 14.04 (Trusty)...I notice poppler is at 0.24?

**Comment by djvs** [comment] 2015-02-23 21:00
Dunno if this is related by the way.  There's no package just named "poppler" on Ubuntu 12.04 or Ubuntu 14.04.  Is there supposed to be?  I'm trying to build this right now to see if it changes anything:

https://launchpad.net/~coolwanglu/+archive/ubuntu/pdf2htmlex/+files/poppler_0.26.5.orig.tar.xz

**Comment by tjsail33** [comment] 2015-02-23 21:39
The instructions for building specify that you must have poppler >=0.25.0, so your version will not work. When installing from source, make sure to run `./configure --with-xpdf-headers` and not just `./configure` The Building docs on the wiki have all of this information.

**Comment by djvs** [comment] 2015-02-23 21:52
I didn't install it from source originally, believe that came right from the repos. 

 Building it from source now though (0.26).

**Comment by djvs** [comment] 2015-02-23 22:02
pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.26.5
  libfontforge 20141118
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg

Same problem!

**Comment by djvs** [comment] 2015-02-23 22:24
CSS issue apparently.  Only in Chrome/Chromium - look at Firefox output.

![2015-02-23-172240_716x837_scrot](https://cloud.githubusercontent.com/assets/2954343/6338976/b3f717ac-bb80-11e4-9f4c-19d50142266d.png)

**Comment by djvs** [comment] 2015-02-23 22:31
This is a major recurring issue, and while I'm not sure what, I strongly suspect there's just one little minor CSS issue at play here...

**Comment by djvs** [comment] 2015-02-23 22:34
.wsa, .wsb,....wse etc., they're getting these word-spacing values like 0.03px.  It completely breaks the formatting!

**Comment by duanyao** [comment] 2015-03-17 17:48
The problem in first file (http://djvs.co/Untitleddocument.pdf) is caused by zero width space.

The PDF contains zero width space character (U+200B). This char by definition has zero width, but according to the font dictionary and embeded font file, its width is not zero, but 1 (means same as font size). This is not a problem in PDF, because PDF just treats zero width space as a normal char, i.e. respects the char width defined in the font dictionary or the font file.

But it seems that browsers *always* display U+200B as zero width, no matter what width is defined in the font file. So in the output html file, characters after U+200B are shifted to left in comparison with the PDF.
I don't know whether this behavior is defined by any web standards, it seems that [CSS Fonts spec](http://dev.w3.org/csswg/css-fonts/) says nothing about this.

One possible solution is, in `HTMLRenderer::drawString()`, append a offset of the width reported by `GfxFont::getNextChar` if we meet U+200B. However, if the font in pdf maps U+200B a visible glyph, we still loose it after conversion.

**Comment by coolwanglu** [comment] 2015-03-18 08:39
@duanyao I can mark it as 'illegal', and never output it in HTML, like what we did for other similar codes: https://github.com/coolwanglu/pdf2htmlEX/blob/incoming/src/util/unicode.cc#L51

**Comment by coolwanglu** [comment] 2015-03-18 08:50
@djvs Can I use this PDF file as a test case for pdf2htmlEX?

**Comment by coolwanglu** [comment] 2015-03-18 10:11
Fixed in the incoming branch. Please have a try.

**Comment by duanyao** [comment] 2015-03-18 10:35
@coolwanglu it seems not enough to just add NBSP, it is a long list, see #488.

**Comment by duanyao** [comment] 2015-03-18 11:43
It is still unforturnate that all white spaces in this PDF becomes weird private unicodes after conversion. I think maybe we can improve this by checking the glyph before mapping a invalid char: if its glyph does not exist or is empty, map the char to a space, otherwise map it to a private unicode.

**Comment by coolwanglu** [comment] 2015-03-18 11:44
If we map it to space, there will be other weird stuffs, say, `word-space`.

**Comment by duanyao** [comment] 2015-03-18 12:06
I think this is not a problem, the mapped spaces also have widths assigned, and CSS `word-spacing`s are calculated based on those widths.

**Comment by coolwanglu** [comment] 2015-03-18 12:08
In the context where both normal spaces, zero-width spaces are used, how can you map zero-width spaces to normal spaces?

**Comment by duanyao** [comment] 2015-03-18 12:15
Both normal spaces and zero-width spaces are mapped to normal spaces, if they all have no glyph. Note that in PDF, zero-width spaces are not neccessarily "zero-width", so it is reasonable to convert them to spaces.

**Comment by coolwanglu** [comment] 2015-03-18 12:16
What if normal spaces and zero-width spaces have different widths defined, as in the font files in PDF?

**Comment by duanyao** [comment] 2015-03-18 12:41
Then some of the spaces will be wrapped in spans, with width assigned.

**Comment by coolwanglu** [comment] 2015-03-18 12:42
@duanyao  I see, so we can just apply `--space-as-offset` to those chars.

**Comment by coolwanglu** [comment] 2015-05-02 07:51
@djvs can you verify with the lastest vesrion? And can we use your PDF as a testcase?

**Comment by djvs** [comment] 2015-05-02 13:49
Nice and clean so far according to user feedback & tests (incoming branch).

**Comment by coolwanglu** [comment] 2015-05-02 14:08
@djvs  How about the PDF file?

**Comment by djvs** [comment] 2015-05-02 14:09
![2015-05-02-100935_982x1040_scrot](https://cloud.githubusercontent.com/assets/2954343/7441363/5caf8b38-f0b3-11e4-89fb-7d42acb73e8b.png)

**Comment by coolwanglu** [comment] 2015-05-02 14:11
@djvs  The screenshot looks good. About the PDF file, I meant we need to make sure that the PDF is available for us to included in the test suites of pdf2htmlEX. Is it the case?

**Comment by djvs** [comment] 2015-05-02 14:22
License-wise?  I'm sure it's no problem, although it seems any PDF with text formatting (bold/italic/sub-or-superscript) will create the same issue when applicable.

**Comment by coolwanglu** [comment] 2015-05-02 14:22
Thanks.

**Closed** 2015-05-03 04:09 UTC
