### ISSUE TITLE
Reader/Viewer Web Application to view output html magazines

### ISSUE THREAD

**Issue by BockwurstJoe** [coolwanglu/pdf2htmlEX#578] opened 2015-09-21 09:48 UTC
Hi all,

I've been looking for a html frame application, I can use to zoom in and out, switch pages and so on.
It would be very nice to have something like pdfjs reader for the html files.

Has anybody worked on something like this? can anyone share his effort or does anyone have an idea, which existing viewer application i could take?

Thank you very much!

**Comment by coolwanglu** [comment] 2016-04-13 18:11
Duplicate of #219

**Closed by coolwanglu** 2016-04-13 18:11 UTC
