### ISSUE TITLE
RTL some characters issue

### ISSUE THREAD

**Issue by farhod** [coolwanglu/pdf2htmlEX#481] opened 2015-03-09 16:51 UTC
Some pages  im processing are not converting correctly. 
Symbols are jumping.
Here is an example: 
[PDF - original](http://cl.faryus.com/pdf/output_38.pdf)
[HTML- converted](http://cl.faryus.com/pdf/outnew/output_38.html)

**Comment by coolwanglu** [comment] 2015-05-03 08:59
I cannot reproduce it. Or it has been fixed in a recent commit in `incoming`.
Please reopen if the problem still exists for the `incoming` branch on your machine.

**Closed by coolwanglu** 2015-05-03 08:59 UTC
